//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendsManager
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class Fault : object
    {
        
        private string DetailsField;
        
        private string ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendRequest", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class FriendRequest : object
    {
        
        private int ReceiverIDField;
        
        private int SenderIDField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiverID
        {
            get
            {
                return this.ReceiverIDField;
            }
            set
            {
                this.ReceiverIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SenderID
        {
            get
            {
                return this.SenderIDField;
            }
            set
            {
                this.SenderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Friendship", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class Friendship : object
    {
        
        private FriendsManager.Player FriendField;
        
        private int PlayerIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriendsManager.Player Friend
        {
            get
            {
                return this.FriendField;
            }
            set
            {
                this.FriendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerID
        {
            get
            {
                return this.PlayerIDField;
            }
            set
            {
                this.PlayerIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class Player : object
    {
        
        private FriendsManager.Friendship[] FriendsField;
        
        private int IsVerifiedField;
        
        private string PlayerAvatarPathField;
        
        private string PlayerEmailField;
        
        private int PlayerIdField;
        
        private string PlayerNameField;
        
        private string PlayerPasswordField;
        
        private string PlayerUsernameField;
        
        private FriendsManager.SocialMedia[] SocialMediaField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriendsManager.Friendship[] Friends
        {
            get
            {
                return this.FriendsField;
            }
            set
            {
                this.FriendsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsVerified
        {
            get
            {
                return this.IsVerifiedField;
            }
            set
            {
                this.IsVerifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerAvatarPath
        {
            get
            {
                return this.PlayerAvatarPathField;
            }
            set
            {
                this.PlayerAvatarPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerEmail
        {
            get
            {
                return this.PlayerEmailField;
            }
            set
            {
                this.PlayerEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId
        {
            get
            {
                return this.PlayerIdField;
            }
            set
            {
                this.PlayerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName
        {
            get
            {
                return this.PlayerNameField;
            }
            set
            {
                this.PlayerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerPassword
        {
            get
            {
                return this.PlayerPasswordField;
            }
            set
            {
                this.PlayerPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerUsername
        {
            get
            {
                return this.PlayerUsernameField;
            }
            set
            {
                this.PlayerUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriendsManager.SocialMedia[] SocialMedia
        {
            get
            {
                return this.SocialMediaField;
            }
            set
            {
                this.SocialMediaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialMedia", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class SocialMedia : object
    {
        
        private int PlayerIdField;
        
        private string SocialLinkField;
        
        private int SocialMediaIdField;
        
        private string SocialMediaNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId
        {
            get
            {
                return this.PlayerIdField;
            }
            set
            {
                this.PlayerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialLink
        {
            get
            {
                return this.SocialLinkField;
            }
            set
            {
                this.SocialLinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SocialMediaId
        {
            get
            {
                return this.SocialMediaIdField;
            }
            set
            {
                this.SocialMediaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialMediaName
        {
            get
            {
                return this.SocialMediaNameField;
            }
            set
            {
                this.SocialMediaNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendsManager.IFriendsManager")]
    public interface IFriendsManager
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/SendFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FriendsManager.Fault), Action="http://tempuri.org/IFriendsManager/SendFriendRequestFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/AcceptFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FriendsManager.Fault), Action="http://tempuri.org/IFriendsManager/AcceptFriendRequestFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> AcceptFriendRequestAsync(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/CancelFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/CancelFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FriendsManager.Fault), Action="http://tempuri.org/IFriendsManager/CancelFriendRequestFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> CancelFriendRequestAsync(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/DeleteFriend", ReplyAction="http://tempuri.org/IFriendsManager/DeleteFriendResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FriendsManager.Fault), Action="http://tempuri.org/IFriendsManager/DeleteFriendFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> DeleteFriendAsync(string friendUsername, string playerUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/GetFriendRequests", ReplyAction="http://tempuri.org/IFriendsManager/GetFriendRequestsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FriendsManager.Fault), Action="http://tempuri.org/IFriendsManager/GetFriendRequestsFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<FriendsManager.FriendRequest[]> GetFriendRequestsAsync(string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/GetFriendsByID", ReplyAction="http://tempuri.org/IFriendsManager/GetFriendsByIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FriendsManager.Fault), Action="http://tempuri.org/IFriendsManager/GetFriendsByIDFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<FriendsManager.Friendship[]> GetFriendsByIDAsync(int playerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IFriendsManagerChannel : FriendsManager.IFriendsManager, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class FriendsManagerClient : System.ServiceModel.ClientBase<FriendsManager.IFriendsManager>, FriendsManager.IFriendsManager
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FriendsManagerClient() : 
                base(FriendsManagerClient.GetDefaultBinding(), FriendsManagerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IFriendsManager.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FriendsManagerClient(EndpointConfiguration endpointConfiguration) : 
                base(FriendsManagerClient.GetBindingForEndpoint(endpointConfiguration), FriendsManagerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FriendsManagerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FriendsManagerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FriendsManagerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FriendsManagerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FriendsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string senderUsername, string receiverUsername)
        {
            return base.Channel.SendFriendRequestAsync(senderUsername, receiverUsername);
        }
        
        public System.Threading.Tasks.Task<bool> AcceptFriendRequestAsync(string senderUsername, string receiverUsername)
        {
            return base.Channel.AcceptFriendRequestAsync(senderUsername, receiverUsername);
        }
        
        public System.Threading.Tasks.Task<bool> CancelFriendRequestAsync(string senderUsername, string receiverUsername)
        {
            return base.Channel.CancelFriendRequestAsync(senderUsername, receiverUsername);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFriendAsync(string friendUsername, string playerUsername)
        {
            return base.Channel.DeleteFriendAsync(friendUsername, playerUsername);
        }
        
        public System.Threading.Tasks.Task<FriendsManager.FriendRequest[]> GetFriendRequestsAsync(string receiverUsername)
        {
            return base.Channel.GetFriendRequestsAsync(receiverUsername);
        }
        
        public System.Threading.Tasks.Task<FriendsManager.Friendship[]> GetFriendsByIDAsync(int playerID)
        {
            return base.Channel.GetFriendsByIDAsync(playerID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IFriendsManager))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IFriendsManager))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://192.168.100.15:8082/FriendsManager");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FriendsManagerClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IFriendsManager);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FriendsManagerClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IFriendsManager);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IFriendsManager,
        }
    }
}
