h//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forbbiden.Client.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forbbiden.Client.Properties.Langs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public.
        /// </summary>
        public static string _public {
            get {
                return ResourceManager.GetString("public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actions Left.
        /// </summary>
        public static string actions_left {
            get {
                return ResourceManager.GetString("actions_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import an image from your device to use as an avatar.
        /// </summary>
        public static string avatar_explanation {
            get {
                return ResourceManager.GetString("avatar_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There were some invalid inputs in your form, check it out.
        /// </summary>
        public static string boss_invalid_inputs {
            get {
                return ResourceManager.GetString("boss_invalid_inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you log in you can choose your avatar and make friends!.
        /// </summary>
        public static string bossLogin {
            get {
                return ResourceManager.GetString("bossLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capture Treasure.
        /// </summary>
        public static string capture_button {
            get {
                return ResourceManager.GetString("capture_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Language.
        /// </summary>
        public static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create room.
        ///   Busca una cadena traducida similar a Clean Code.
        /// </summary>
        public static string clean_code_name {
            get {
                return ResourceManager.GetString("clean-code-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create room.
        /// </summary>
        public static string create_room {
            get {
                return ResourceManager.GetString("create_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        ///   Busca una cadena traducida similar a Cubicle Keys.
        /// </summary>
        public static string cubicle_keys_name {
            get {
                return ResourceManager.GetString("cubicle-keys-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difficulty.
        /// </summary>
        public static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discard a Card.
        /// </summary>
        public static string discard_card {
            get {
                return ResourceManager.GetString("discard_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discard Changes.
        /// </summary>
        public static string discard_changes {
            get {
                return ResourceManager.GetString("discard_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To avoid drowning you have to move to another tile... ¡NOW!.
        /// </summary>
        public static string emergency_move {
            get {
                return ResourceManager.GetString("emergency_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You Are Drowning!.
        /// </summary>
        public static string emergency_move_title {
            get {
                return ResourceManager.GetString("emergency_move_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish Turn.
        /// </summary>
        public static string finish_turn {
            get {
                return ResourceManager.GetString("finish_turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flood Stack.
        /// </summary>
        public static string flood_stack {
            get {
                return ResourceManager.GetString("flood_stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have successfully deleted your friendship with: .
        /// </summary>
        public static string friend_deleted_message {
            get {
                return ResourceManager.GetString("friend_deleted_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Deleted.
        /// </summary>
        public static string friend_deleted_title {
            get {
                return ResourceManager.GetString("friend_deleted_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Request Accepted.
        /// </summary>
        public static string friend_request_accepted {
            get {
                return ResourceManager.GetString("friend_request_accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The friend request was accepted succesfully.
        /// </summary>
        public static string friend_request_accepted_message {
            get {
                return ResourceManager.GetString("friend_request_accepted_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error while sending your friend request, try again later.
        /// </summary>
        public static string friend_request_not_sent {
            get {
                return ResourceManager.GetString("friend_request_not_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your friend request was successfully sent to .
        /// </summary>
        public static string friend_request_sent_message {
            get {
                return ResourceManager.GetString("friend_request_sent_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Request Sent.
        /// </summary>
        public static string friend_request_sent_title {
            get {
                return ResourceManager.GetString("friend_request_sent_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Requests.
        /// </summary>
        public static string friend_requests {
            get {
                return ResourceManager.GetString("friend_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string friends {
            get {
                return ResourceManager.GetString("friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GAME OVER!.
        /// </summary>
        public static string game_over {
            get {
                return ResourceManager.GetString("game_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The water reach the highest level! FEI IS NOW UNDER THE SEAS! Good Luck in your next adventure....
        /// </summary>
        public static string game_over_message {
            get {
                return ResourceManager.GetString("game_over_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string guest {
            get {
                return ResourceManager.GetString("guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hard.
        /// </summary>
        public static string hard {
            get {
                return ResourceManager.GetString("hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The water level starts at 3.
        /// </summary>
        public static string hard_message {
            get {
                return ResourceManager.GetString("hard_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host Game.
        /// </summary>
        public static string host_game {
            get {
                return ResourceManager.GetString("host_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Input.
        /// </summary>
        public static string invalid_input {
            get {
                return ResourceManager.GetString("invalid_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keep cards.
        /// </summary>
        public static string keep_cards {
            get {
                return ResourceManager.GetString("keep_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error while loading the page, try again or contact us at: forbbidenislandfei@gmail.com.
        /// </summary>
        public static string load_page_error {
            get {
                return ResourceManager.GetString("load_page_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while logging out at data base.
        /// </summary>
        public static string log_out_error {
            get {
                return ResourceManager.GetString("log_out_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string login_button {
            get {
                return ResourceManager.GetString("login_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login error. Please try again.
        /// </summary>
        public static string loginError {
            get {
                return ResourceManager.GetString("loginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lucio.
        /// </summary>
        public static string lucio_name {
            get {
                return ResourceManager.GetString("lucio-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Too much cards!.
        /// </summary>
        public static string max_cards_exceed {
            get {
                return ResourceManager.GetString("max_cards_exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With this card you will have more than six cards, what do you want to do?.
        /// </summary>
        public static string max_cards_exceed_message {
            get {
                return ResourceManager.GetString("max_cards_exceed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max number of Players.
        /// </summary>
        public static string max_players {
            get {
                return ResourceManager.GetString("max_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You haven&apos;t captured the four treasures at the FEI.
        /// </summary>
        public static string missing_treasures {
            get {
                return ResourceManager.GetString("missing_treasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing Treasures.
        /// </summary>
        public static string missing_treasures_title {
            get {
                return ResourceManager.GetString("missing_treasures_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move.
        /// </summary>
        public static string move_button {
            get {
                return ResourceManager.GetString("move_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Game.
        /// </summary>
        public static string new_game {
            get {
                return ResourceManager.GetString("new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You ran out of actions, you have to steal treasure cards from the Treasure Stack (click on it).
        /// </summary>
        public static string no_more_actions {
            get {
                return ResourceManager.GetString("no_more_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        public static string normal {
            get {
                return ResourceManager.GetString("normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The water level starts at 1.
        /// </summary>
        public static string normal_message {
            get {
                return ResourceManager.GetString("normal_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You don&apos;t have at least two cards of the treasure you are trying to capture.
        /// </summary>
        public static string not_enough_treasure_cards {
            get {
                return ResourceManager.GetString("not_enough_treasure_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing Treasure Cards.
        /// </summary>
        public static string not_enough_treasure_cards_title {
            get {
                return ResourceManager.GetString("not_enough_treasure_cards_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To escape from the FEI you have to be at the FEI Entrance (blue border tile).
        /// </summary>
        public static string not_escape_tile {
            get {
                return ResourceManager.GetString("not_escape_tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not a Escape Tile.
        /// </summary>
        public static string not_escape_tile_title {
            get {
                return ResourceManager.GetString("not_escape_tile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To capture a treasure you have to be at a treasure tile.
        /// </summary>
        public static string not_treasure_tile {
            get {
                return ResourceManager.GetString("not_treasure_tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not a Treasure Tile.
        /// </summary>
        public static string not_treasure_tile_title {
            get {
                return ResourceManager.GetString("not_treasure_tile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It&apos;s not your turn yet, wait a little bit!.
        /// </summary>
        public static string not_your_turn_message {
            get {
                return ResourceManager.GetString("not_your_turn_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It&apos;s Not Your Turn.
        /// </summary>
        public static string not_your_turn_title {
            get {
                return ResourceManager.GetString("not_your_turn_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string offline {
            get {
                return ResourceManager.GetString("offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string online_friends {
            get {
                return ResourceManager.GetString("online_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parking Card.
        /// </summary>
        public static string parking_card_name {
            get {
                return ResourceManager.GetString("parking-card-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick a card.
        /// </summary>
        public static string pick_card {
            get {
                return ResourceManager.GetString("pick_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player Verified.
        /// </summary>
        public static string player_verified {
            get {
                return ResourceManager.GetString("player verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been successfully verified.
        /// </summary>
        public static string player_verified_message {
            get {
                return ResourceManager.GetString("player_verified_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only the players with invitation can join .
        /// </summary>
        public static string private_message {
            get {
                return ResourceManager.GetString("private_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Any player can join in your game.
        /// </summary>
        public static string public_message {
            get {
                return ResourceManager.GetString("public_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error while retrieving info from the database.
        /// </summary>
        public static string pull_database_error {
            get {
                return ResourceManager.GetString("pull_database_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error while writing info to the database.
        /// </summary>
        public static string push_database_error {
            get {
                return ResourceManager.GetString("push_database_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit game.
        /// </summary>
        public static string quit_game {
            get {
                return ResourceManager.GetString("quit_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while closing application.
        /// </summary>
        public static string quit_game_error {
            get {
                return ResourceManager.GetString("quit_game_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember Me.
        /// </summary>
        public static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Room name.
        /// </summary>
        public static string room_name {
            get {
                return ResourceManager.GetString("room_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        public static string save_changes {
            get {
                return ResourceManager.GetString("save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search_btn_text {
            get {
                return ResourceManager.GetString("search_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by room name or host....
        /// </summary>
        public static string search_placeholder {
            get {
                return ResourceManager.GetString("search_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Language.
        /// </summary>
        public static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error while sending your verification email, contact us at: forbbidenislandfei@gmail.com.
        /// </summary>
        public static string send_email_error {
            get {
                return ResourceManager.GetString("send_email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shore up.
        /// </summary>
        public static string shore_up_button {
            get {
                return ResourceManager.GetString("shore_up_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show.
        /// </summary>
        public static string show_password {
            get {
                return ResourceManager.GetString("show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string signup_button {
            get {
                return ResourceManager.GetString("signup_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user name can&apos;t be empty.
        /// </summary>
        public static string signup_empty_username {
            get {
                return ResourceManager.GetString("signup_empty_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error while signing up, try again later.
        /// </summary>
        public static string signup_error {
            get {
                return ResourceManager.GetString("signup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email is not valid or is already registered.
        /// </summary>
        public static string signup_invalid_email {
            get {
                return ResourceManager.GetString("signup_invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must have at least 8 characters, one upper case, one lower case, one number and one special character (@, &amp;, _).
        /// </summary>
        public static string signup_invalid_password {
            get {
                return ResourceManager.GetString("signup_invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user name can&apos;t contain white spaces ( ).
        /// </summary>
        public static string signup_space_username {
            get {
                return ResourceManager.GetString("signup_space_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string signup_title {
            get {
                return ResourceManager.GetString("signup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a That user name is already being used.
        /// </summary>
        public static string signup_username_already_used {
            get {
                return ResourceManager.GetString("signup_username_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful Sign-Up.
        /// </summary>
        public static string successful_signup {
            get {
                return ResourceManager.GetString("successful_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The sign-up was successful, now you can log in.
        /// </summary>
        public static string successful_signup_message {
            get {
                return ResourceManager.GetString("successful_signup_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Treasures Saved.
        /// </summary>
        public static string treasures_saved {
            get {
                return ResourceManager.GetString("treasures_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an unexpected error, please contact client support.
        /// </summary>
        public static string unexpected_error {
            get {
                return ResourceManager.GetString("unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload Avatar.
        /// </summary>
        public static string upload_avatar {
            get {
                return ResourceManager.GetString("upload_avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use Card.
        /// </summary>
        public static string use_card {
            get {
                return ResourceManager.GetString("use_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username or email.
        /// </summary>
        public static string username_email {
            get {
                return ResourceManager.GetString("username_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username does not exists.
        /// </summary>
        public static string usernameNoExists {
            get {
                return ResourceManager.GetString("usernameNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have sent you a new verification token, please check your email.
        /// </summary>
        public static string verification_token_sent {
            get {
                return ResourceManager.GetString("verification_token_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification Token Sent.
        /// </summary>
        public static string verification_token_sent_title {
            get {
                return ResourceManager.GetString("verification_token_sent_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify.
        /// </summary>
        public static string verify {
            get {
                return ResourceManager.GetString("verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Account.
        /// </summary>
        public static string verify_account {
            get {
                return ResourceManager.GetString("verify_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility.
        /// </summary>
        public static string visibility {
            get {
                return ResourceManager.GetString("visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Water Level.
        /// </summary>
        public static string water_level {
            get {
                return ResourceManager.GetString("water_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have saved all the treasures at the school! Thanks for playing!.
        /// </summary>
        public static string win_message {
            get {
                return ResourceManager.GetString("win_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You Win!.
        /// </summary>
        public static string win_title {
            get {
                return ResourceManager.GetString("win_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong Token.
        /// </summary>
        public static string wrong_token {
            get {
                return ResourceManager.GetString("wrong_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The token you try to verify is not correct, please try again.
        /// </summary>
        public static string wrong_token_message {
            get {
                return ResourceManager.GetString("wrong_token_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong Password.
        /// </summary>
        public static string wrongPassword {
            get {
                return ResourceManager.GetString("wrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have drowned, better luck next time!.
        /// </summary>
        public static string you_drowned_message {
            get {
                return ResourceManager.GetString("you_drowned_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It&apos;s your turn to play! Choose wisely your actions.
        /// </summary>
        public static string your_turn_message {
            get {
                return ResourceManager.GetString("your_turn_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Turn!.
        /// </summary>
        public static string your_turn_title {
            get {
                return ResourceManager.GetString("your_turn_title", resourceCulture);
            }
        }
    }
}
