//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forbbiden.Client.TokenManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    [System.SerializableAttribute()]
    public partial class Token : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenString {
            get {
                return this.TokenStringField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenStringField, value) != true)) {
                    this.TokenStringField = value;
                    this.RaisePropertyChanged("TokenString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TokenManager.ITokenManager")]
    public interface ITokenManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/CreateRandomToken", ReplyAction="http://tempuri.org/ITokenManager/CreateRandomTokenResponse")]
        string CreateRandomToken();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/CreateRandomToken", ReplyAction="http://tempuri.org/ITokenManager/CreateRandomTokenResponse")]
        System.Threading.Tasks.Task<string> CreateRandomTokenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/GenerateToken", ReplyAction="http://tempuri.org/ITokenManager/GenerateTokenResponse")]
        Forbbiden.Client.TokenManager.Token GenerateToken(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/GenerateToken", ReplyAction="http://tempuri.org/ITokenManager/GenerateTokenResponse")]
        System.Threading.Tasks.Task<Forbbiden.Client.TokenManager.Token> GenerateTokenAsync(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/GetToken", ReplyAction="http://tempuri.org/ITokenManager/GetTokenResponse")]
        Forbbiden.Client.TokenManager.Token GetToken(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/GetToken", ReplyAction="http://tempuri.org/ITokenManager/GetTokenResponse")]
        System.Threading.Tasks.Task<Forbbiden.Client.TokenManager.Token> GetTokenAsync(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/VerifyToken", ReplyAction="http://tempuri.org/ITokenManager/VerifyTokenResponse")]
        bool VerifyToken(string token, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/VerifyToken", ReplyAction="http://tempuri.org/ITokenManager/VerifyTokenResponse")]
        System.Threading.Tasks.Task<bool> VerifyTokenAsync(string token, int playerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokenManagerChannel : Forbbiden.Client.TokenManager.ITokenManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenManagerClient : System.ServiceModel.ClientBase<Forbbiden.Client.TokenManager.ITokenManager>, Forbbiden.Client.TokenManager.ITokenManager {
        
        public TokenManagerClient() {
        }
        
        public TokenManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateRandomToken() {
            return base.Channel.CreateRandomToken();
        }
        
        public System.Threading.Tasks.Task<string> CreateRandomTokenAsync() {
            return base.Channel.CreateRandomTokenAsync();
        }
        
        public Forbbiden.Client.TokenManager.Token GenerateToken(int playerId) {
            return base.Channel.GenerateToken(playerId);
        }
        
        public System.Threading.Tasks.Task<Forbbiden.Client.TokenManager.Token> GenerateTokenAsync(int playerId) {
            return base.Channel.GenerateTokenAsync(playerId);
        }
        
        public Forbbiden.Client.TokenManager.Token GetToken(int playerId) {
            return base.Channel.GetToken(playerId);
        }
        
        public System.Threading.Tasks.Task<Forbbiden.Client.TokenManager.Token> GetTokenAsync(int playerId) {
            return base.Channel.GetTokenAsync(playerId);
        }
        
        public bool VerifyToken(string token, int playerId) {
            return base.Channel.VerifyToken(token, playerId);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyTokenAsync(string token, int playerId) {
            return base.Channel.VerifyTokenAsync(token, playerId);
        }
    }
}
