//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForbbidenIslandFEI_Construction
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class match_minigames
    {
        public int match_minigames_id { get; set; }
        public int match_id { get; set; }
        public int minigame_id { get; set; }
    
        public virtual minigame minigame { get; set; }
        public virtual matches matches { get; set; }
    }
}
