//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenManager
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class Token : object
    {
        
        private int IdField;
        
        private int PlayerIdField;
        
        private string TokenStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId
        {
            get
            {
                return this.PlayerIdField;
            }
            set
            {
                this.PlayerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenString
        {
            get
            {
                return this.TokenStringField;
            }
            set
            {
                this.TokenStringField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TokenManager.ITokenManager")]
    public interface ITokenManager
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/CreateRandomToken", ReplyAction="http://tempuri.org/ITokenManager/CreateRandomTokenResponse")]
        System.Threading.Tasks.Task<string> CreateRandomTokenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/GenerateToken", ReplyAction="http://tempuri.org/ITokenManager/GenerateTokenResponse")]
        System.Threading.Tasks.Task<TokenManager.Token> GenerateTokenAsync(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/GetToken", ReplyAction="http://tempuri.org/ITokenManager/GetTokenResponse")]
        System.Threading.Tasks.Task<TokenManager.Token> GetTokenAsync(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenManager/VerifyToken", ReplyAction="http://tempuri.org/ITokenManager/VerifyTokenResponse")]
        System.Threading.Tasks.Task<bool> VerifyTokenAsync(string token, int playerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ITokenManagerChannel : TokenManager.ITokenManager, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TokenManagerClient : System.ServiceModel.ClientBase<TokenManager.ITokenManager>, TokenManager.ITokenManager
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TokenManagerClient() : 
                base(TokenManagerClient.GetDefaultBinding(), TokenManagerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_ITokenManager.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokenManagerClient(EndpointConfiguration endpointConfiguration) : 
                base(TokenManagerClient.GetBindingForEndpoint(endpointConfiguration), TokenManagerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokenManagerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TokenManagerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokenManagerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TokenManagerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokenManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> CreateRandomTokenAsync()
        {
            return base.Channel.CreateRandomTokenAsync();
        }
        
        public System.Threading.Tasks.Task<TokenManager.Token> GenerateTokenAsync(int playerId)
        {
            return base.Channel.GenerateTokenAsync(playerId);
        }
        
        public System.Threading.Tasks.Task<TokenManager.Token> GetTokenAsync(int playerId)
        {
            return base.Channel.GetTokenAsync(playerId);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyTokenAsync(string token, int playerId)
        {
            return base.Channel.VerifyTokenAsync(token, playerId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ITokenManager))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ITokenManager))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://localhost:8085/TokenManager");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TokenManagerClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_ITokenManager);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TokenManagerClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_ITokenManager);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_ITokenManager,
        }
    }
}
