//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forbbiden.Client.FriendsManager {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendsManager.IFriendsManager")]
    public interface IFriendsManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/SendFriendRequestResponse")]
        bool SendFriendRequest(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/AcceptFriendRequestResponse")]
        bool AcceptFriendRequest(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/AcceptFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> AcceptFriendRequestAsync(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/CancelFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/CancelFriendRequestResponse")]
        bool CancelFriendRequest(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/CancelFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/CancelFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> CancelFriendRequestAsync(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/getFriendRequests", ReplyAction="http://tempuri.org/IFriendsManager/getFriendRequestsResponse")]
        Forbbiden.Contracts.FriendRequest[] getFriendRequests(string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/getFriendRequests", ReplyAction="http://tempuri.org/IFriendsManager/getFriendRequestsResponse")]
        System.Threading.Tasks.Task<Forbbiden.Contracts.FriendRequest[]> getFriendRequestsAsync(string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/getFriendsByID", ReplyAction="http://tempuri.org/IFriendsManager/getFriendsByIDResponse")]
        Forbbiden.Contracts.Friendship[] getFriendsByID(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/getFriendsByID", ReplyAction="http://tempuri.org/IFriendsManager/getFriendsByIDResponse")]
        System.Threading.Tasks.Task<Forbbiden.Contracts.Friendship[]> getFriendsByIDAsync(int playerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendsManagerChannel : Forbbiden.Client.FriendsManager.IFriendsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendsManagerClient : System.ServiceModel.ClientBase<Forbbiden.Client.FriendsManager.IFriendsManager>, Forbbiden.Client.FriendsManager.IFriendsManager {
        
        public FriendsManagerClient() {
        }
        
        public FriendsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FriendsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendFriendRequest(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequest(senderUsername, receiverUsername);
        }
        
        public System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequestAsync(senderUsername, receiverUsername);
        }
        
        public bool AcceptFriendRequest(string senderUsername, string receiverUsername) {
            return base.Channel.AcceptFriendRequest(senderUsername, receiverUsername);
        }
        
        public System.Threading.Tasks.Task<bool> AcceptFriendRequestAsync(string senderUsername, string receiverUsername) {
            return base.Channel.AcceptFriendRequestAsync(senderUsername, receiverUsername);
        }
        
        public bool CancelFriendRequest(string senderUsername, string receiverUsername) {
            return base.Channel.CancelFriendRequest(senderUsername, receiverUsername);
        }
        
        public System.Threading.Tasks.Task<bool> CancelFriendRequestAsync(string senderUsername, string receiverUsername) {
            return base.Channel.CancelFriendRequestAsync(senderUsername, receiverUsername);
        }
        
        public Forbbiden.Contracts.FriendRequest[] getFriendRequests(string receiverUsername) {
            return base.Channel.getFriendRequests(receiverUsername);
        }
        
        public System.Threading.Tasks.Task<Forbbiden.Contracts.FriendRequest[]> getFriendRequestsAsync(string receiverUsername) {
            return base.Channel.getFriendRequestsAsync(receiverUsername);
        }
        
        public Forbbiden.Contracts.Friendship[] getFriendsByID(int playerID) {
            return base.Channel.getFriendsByID(playerID);
        }
        
        public System.Threading.Tasks.Task<Forbbiden.Contracts.Friendship[]> getFriendsByIDAsync(int playerID) {
            return base.Channel.getFriendsByIDAsync(playerID);
        }
    }
}
