//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forbbiden.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forbbiden.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string _public {
            get {
                return ResourceManager.GetString("public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions Left.
        /// </summary>
        internal static string actions_left {
            get {
                return ResourceManager.GetString("actions_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import an image from your device to use as an avatar.
        /// </summary>
        internal static string avatar_explanation {
            get {
                return ResourceManager.GetString("avatar_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some invalid inputs in your form, check it out.
        /// </summary>
        internal static string boss_invalid_inputs {
            get {
                return ResourceManager.GetString("boss_invalid_inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you log in you can choose your avatar and make friends!.
        /// </summary>
        internal static string bossLogin {
            get {
                return ResourceManager.GetString("bossLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Treasure.
        /// </summary>
        internal static string capture_button {
            get {
                return ResourceManager.GetString("capture_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player:.
        /// </summary>
        internal static string chat_prefix_placeholder {
            get {
                return ResourceManager.GetString("chat_prefix_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending message..
        /// </summary>
        internal static string chat_send_error {
            get {
                return ResourceManager.GetString("chat_send_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Code.
        /// </summary>
        internal static string clean_code_name {
            get {
                return ResourceManager.GetString("clean_code_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting match!.
        /// </summary>
        internal static string countdown_go {
            get {
                return ResourceManager.GetString("countdown_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting in {0}....
        /// </summary>
        internal static string countdown_number {
            get {
                return ResourceManager.GetString("countdown_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting countdown....
        /// </summary>
        internal static string countdown_starting {
            get {
                return ResourceManager.GetString("countdown_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create room.
        /// </summary>
        internal static string create_room {
            get {
                return ResourceManager.GetString("create_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubicle Keys.
        /// </summary>
        internal static string cubicle_keys_name {
            get {
                return ResourceManager.GetString("cubicle_keys_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string difficulty_normal {
            get {
                return ResourceManager.GetString("difficulty_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard a Card.
        /// </summary>
        internal static string discard_card {
            get {
                return ResourceManager.GetString("discard_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        internal static string discard_changes {
            get {
                return ResourceManager.GetString("discard_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To avoid drowning you have to move to another tile... ¡NOW!.
        /// </summary>
        internal static string emergency_move {
            get {
                return ResourceManager.GetString("emergency_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Drowning!.
        /// </summary>
        internal static string emergency_move_title {
            get {
                return ResourceManager.GetString("emergency_move_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading matches: {0}.
        /// </summary>
        internal static string error_loading_matches {
            get {
                return ResourceManager.GetString("error_loading_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Turn.
        /// </summary>
        internal static string finish_turn {
            get {
                return ResourceManager.GetString("finish_turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Stack.
        /// </summary>
        internal static string flood_stack {
            get {
                return ResourceManager.GetString("flood_stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully deleted your friendship with: .
        /// </summary>
        internal static string friend_deleted_message {
            get {
                return ResourceManager.GetString("friend_deleted_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Deleted.
        /// </summary>
        internal static string friend_deleted_title {
            get {
                return ResourceManager.GetString("friend_deleted_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Request Accepted.
        /// </summary>
        internal static string friend_request_accepted {
            get {
                return ResourceManager.GetString("friend_request_accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The friend request was accepted succesfully.
        /// </summary>
        internal static string friend_request_accepted_message {
            get {
                return ResourceManager.GetString("friend_request_accepted_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while sending your friend request, try again later.
        /// </summary>
        internal static string friend_request_not_sent {
            get {
                return ResourceManager.GetString("friend_request_not_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend request was successfully sent to .
        /// </summary>
        internal static string friend_request_sent_message {
            get {
                return ResourceManager.GetString("friend_request_sent_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Request Sent.
        /// </summary>
        internal static string friend_request_sent_title {
            get {
                return ResourceManager.GetString("friend_request_sent_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Requests.
        /// </summary>
        internal static string friend_requests {
            get {
                return ResourceManager.GetString("friend_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string friends {
            get {
                return ResourceManager.GetString("friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME OVER!.
        /// </summary>
        internal static string game_over {
            get {
                return ResourceManager.GetString("game_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The water reach the highest level! FEI IS NOW UNDER THE SEAS! Good Luck in your next adventure....
        /// </summary>
        internal static string game_over_message {
            get {
                return ResourceManager.GetString("game_over_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIUV LOGIN.
        /// </summary>
        internal static string gameTutorial_ControlsHeader {
            get {
                return ResourceManager.GetString("gameTutorial_ControlsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your keyboard and press the indicated key..
        /// </summary>
        internal static string gameTutorial_ControlsText {
            get {
                return ResourceManager.GetString("gameTutorial_ControlsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration date has arrived — retrieve the RIUV password as quickly as possible so you can complete your registration..
        /// </summary>
        internal static string gameTutorial_Description {
            get {
                return ResourceManager.GetString("gameTutorial_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string gameTutorial_Key_Enter {
            get {
                return ResourceManager.GetString("gameTutorial_Key_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string gameTutorial_Key_Separator {
            get {
                return ResourceManager.GetString("gameTutorial_Key_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacebar.
        /// </summary>
        internal static string gameTutorial_Key_Space {
            get {
                return ResourceManager.GetString("gameTutorial_Key_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the match?.
        /// </summary>
        internal static string gameTutorial_Key_Start {
            get {
                return ResourceManager.GetString("gameTutorial_Key_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIUV LOGIN.
        /// </summary>
        internal static string gameTutorial_Title {
            get {
                return ResourceManager.GetString("gameTutorial_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        internal static string guest {
            get {
                return ResourceManager.GetString("guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string hard {
            get {
                return ResourceManager.GetString("hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The water level starts at 3.
        /// </summary>
        internal static string hard_message {
            get {
                return ResourceManager.GetString("hard_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Game.
        /// </summary>
        internal static string host_game {
            get {
                return ResourceManager.GetString("host_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host: .
        /// </summary>
        internal static string host_label {
            get {
                return ResourceManager.GetString("host_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host left the match. Returning to the main menu..
        /// </summary>
        internal static string host_left_message {
            get {
                return ResourceManager.GetString("host_left_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match ended.
        /// </summary>
        internal static string host_left_title {
            get {
                return ResourceManager.GetString("host_left_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string host_unknown {
            get {
                return ResourceManager.GetString("host_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string info_title {
            get {
                return ResourceManager.GetString("info_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you typed has multiple @, verify the format please.
        /// </summary>
        internal static string invalid_email_contains_multiple_at {
            get {
                return ResourceManager.GetString("invalid_email_contains_multiple_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already registered, you cant&apos; use that one.
        /// </summary>
        internal static string invalid_email_not_available {
            get {
                return ResourceManager.GetString("invalid_email_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you typed doesn&apos;t has an @, verify the format please.
        /// </summary>
        internal static string invalid_email_not_contains_at {
            get {
                return ResourceManager.GetString("invalid_email_not_contains_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you typed doesn&apos;t has an extension, verify the format please.
        /// </summary>
        internal static string invalid_email_not_contains_extension {
            get {
                return ResourceManager.GetString("invalid_email_not_contains_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is empty. You have to type an email.
        /// </summary>
        internal static string invalid_empty_email {
            get {
                return ResourceManager.GetString("invalid_empty_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name can&apos;t be empty.
        /// </summary>
        internal static string invalid_empty_username {
            get {
                return ResourceManager.GetString("invalid_empty_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        internal static string invalid_input {
            get {
                return ResourceManager.GetString("invalid_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field is empty. You have to type a password.
        /// </summary>
        internal static string invalid_password_empty {
            get {
                return ResourceManager.GetString("invalid_password_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must have at least one lowercase letter.
        /// </summary>
        internal static string invalid_password_missing_lowercase {
            get {
                return ResourceManager.GetString("invalid_password_missing_lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must have at least one number.
        /// </summary>
        internal static string invalid_password_missing_number {
            get {
                return ResourceManager.GetString("invalid_password_missing_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must have at least one special character (@, _, -).
        /// </summary>
        internal static string invalid_password_missing_special_character {
            get {
                return ResourceManager.GetString("invalid_password_missing_special_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must have at least one uppercase letter.
        /// </summary>
        internal static string invalid_password_missing_uppercase {
            get {
                return ResourceManager.GetString("invalid_password_missing_uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too short, it has to be at least 8 characters long.
        /// </summary>
        internal static string invalid_password_too_short {
            get {
                return ResourceManager.GetString("invalid_password_too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name can&apos;t contain white spaces ( ).
        /// </summary>
        internal static string invalid_username_contains_whitespace {
            get {
                return ResourceManager.GetString("invalid_username_contains_whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation code:.
        /// </summary>
        internal static string invite_code_label {
            get {
                return ResourceManager.GetString("invite_code_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this code with your friends: {0}.
        /// </summary>
        internal static string invite_code_message {
            get {
                return ResourceManager.GetString("invite_code_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string invite_code_not_available {
            get {
                return ResourceManager.GetString("invite_code_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the invitation code to join..
        /// </summary>
        internal static string invite_code_prompt {
            get {
                return ResourceManager.GetString("invite_code_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation code.
        /// </summary>
        internal static string invite_code_title {
            get {
                return ResourceManager.GetString("invite_code_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invitation code is not valid..
        /// </summary>
        internal static string invite_invalid_message {
            get {
                return ResourceManager.GetString("invite_invalid_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        internal static string invite_invalid_title {
            get {
                return ResourceManager.GetString("invite_invalid_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot join this match (you were removed by the host)..
        /// </summary>
        internal static string join_banned_message {
            get {
                return ResourceManager.GetString("join_banned_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot join match.
        /// </summary>
        internal static string join_banned_title {
            get {
                return ResourceManager.GetString("join_banned_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error joining the match: {0}.
        /// </summary>
        internal static string join_error {
            get {
                return ResourceManager.GetString("join_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not join the match..
        /// </summary>
        internal static string join_failed {
            get {
                return ResourceManager.GetString("join_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match is full..
        /// </summary>
        internal static string join_full {
            get {
                return ResourceManager.GetString("join_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match is full. Please choose another room..
        /// </summary>
        internal static string join_full_message {
            get {
                return ResourceManager.GetString("join_full_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match full.
        /// </summary>
        internal static string join_full_title {
            get {
                return ResourceManager.GetString("join_full_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must sign in to join a match..
        /// </summary>
        internal static string join_need_login {
            get {
                return ResourceManager.GetString("join_need_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep cards.
        /// </summary>
        internal static string keep_cards {
            get {
                return ResourceManager.GetString("keep_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were removed from the match by the host..
        /// </summary>
        internal static string kicked_message {
            get {
                return ResourceManager.GetString("kicked_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from match.
        /// </summary>
        internal static string kicked_title {
            get {
                return ResourceManager.GetString("kicked_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string leave_menu_continue {
            get {
                return ResourceManager.GetString("leave_menu_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick player.
        /// </summary>
        internal static string leave_menu_kick_button {
            get {
                return ResourceManager.GetString("leave_menu_kick_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a player from this match..
        /// </summary>
        internal static string leave_menu_kick_desc {
            get {
                return ResourceManager.GetString("leave_menu_kick_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player could not be removed. Please try again..
        /// </summary>
        internal static string leave_menu_kick_fail_msg {
            get {
                return ResourceManager.GetString("leave_menu_kick_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove.
        /// </summary>
        internal static string leave_menu_kick_fail_title {
            get {
                return ResourceManager.GetString("leave_menu_kick_fail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a player to remove..
        /// </summary>
        internal static string leave_menu_kick_no_selection_msg {
            get {
                return ResourceManager.GetString("leave_menu_kick_no_selection_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No player selected.
        /// </summary>
        internal static string leave_menu_kick_no_selection_title {
            get {
                return ResourceManager.GetString("leave_menu_kick_no_selection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No players available to kick..
        /// </summary>
        internal static string leave_menu_kick_none {
            get {
                return ResourceManager.GetString("leave_menu_kick_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player has already left the match. No action taken..
        /// </summary>
        internal static string leave_menu_kick_not_found_msg {
            get {
                return ResourceManager.GetString("leave_menu_kick_not_found_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player not found.
        /// </summary>
        internal static string leave_menu_kick_not_found_title {
            get {
                return ResourceManager.GetString("leave_menu_kick_not_found_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a player to remove (feature pending)..
        /// </summary>
        internal static string leave_menu_kick_placeholder {
            get {
                return ResourceManager.GetString("leave_menu_kick_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was removed from the match..
        /// </summary>
        internal static string leave_menu_kick_success_msg {
            get {
                return ResourceManager.GetString("leave_menu_kick_success_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player removed.
        /// </summary>
        internal static string leave_menu_kick_success_title {
            get {
                return ResourceManager.GetString("leave_menu_kick_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage players.
        /// </summary>
        internal static string leave_menu_kick_title {
            get {
                return ResourceManager.GetString("leave_menu_kick_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string leave_menu_leave {
            get {
                return ResourceManager.GetString("leave_menu_leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you leave, you will exit the current room..
        /// </summary>
        internal static string leave_menu_message {
            get {
                return ResourceManager.GetString("leave_menu_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the match?.
        /// </summary>
        internal static string leave_menu_title {
            get {
                return ResourceManager.GetString("leave_menu_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while loading the page, try again or contact us at: forbbidenislandfei@gmail.com.
        /// </summary>
        internal static string load_page_error {
            get {
                return ResourceManager.GetString("load_page_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while loading the matches, try again later or contact tech support.
        /// </summary>
        internal static string loading_matches_error {
            get {
                return ResourceManager.GetString("loading_matches_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the lobby.
        /// </summary>
        internal static string lobby_welcome {
            get {
                return ResourceManager.GetString("lobby_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while logging out at data base.
        /// </summary>
        internal static string log_out_error {
            get {
                return ResourceManager.GetString("log_out_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string login_button {
            get {
                return ResourceManager.GetString("login_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error. Please try again.
        /// </summary>
        internal static string loginError {
            get {
                return ResourceManager.GetString("loginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucio.
        /// </summary>
        internal static string lucio_name {
            get {
                return ResourceManager.GetString("lucio_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match not found..
        /// </summary>
        internal static string match_not_found {
            get {
                return ResourceManager.GetString("match_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much cards!.
        /// </summary>
        internal static string max_cards_exceed {
            get {
                return ResourceManager.GetString("max_cards_exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this card you will have more than six cards, what do you want to do?.
        /// </summary>
        internal static string max_cards_exceed_message {
            get {
                return ResourceManager.GetString("max_cards_exceed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of Players.
        /// </summary>
        internal static string max_players {
            get {
                return ResourceManager.GetString("max_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a room name (max 20 characters)..
        /// </summary>
        internal static string missing_room_name_message {
            get {
                return ResourceManager.GetString("missing_room_name_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name required.
        /// </summary>
        internal static string missing_room_name_title {
            get {
                return ResourceManager.GetString("missing_room_name_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t captured the four treasures at the FEI.
        /// </summary>
        internal static string missing_treasures {
            get {
                return ResourceManager.GetString("missing_treasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Treasures.
        /// </summary>
        internal static string missing_treasures_title {
            get {
                return ResourceManager.GetString("missing_treasures_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string move_button {
            get {
                return ResourceManager.GetString("move_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string new_game {
            get {
                return ResourceManager.GetString("new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You ran out of actions, you have to steal treasure cards from the Treasure Stack (click on it).
        /// </summary>
        internal static string no_more_actions {
            get {
                return ResourceManager.GetString("no_more_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string normal {
            get {
                return ResourceManager.GetString("normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The water level starts at 1.
        /// </summary>
        internal static string normal_message {
            get {
                return ResourceManager.GetString("normal_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have at least two cards of the treasure you are trying to capture.
        /// </summary>
        internal static string not_enough_treasure_cards {
            get {
                return ResourceManager.GetString("not_enough_treasure_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Treasure Cards.
        /// </summary>
        internal static string not_enough_treasure_cards_title {
            get {
                return ResourceManager.GetString("not_enough_treasure_cards_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To escape from the FEI you have to be at the FEI Entrance (blue border tile).
        /// </summary>
        internal static string not_escape_tile {
            get {
                return ResourceManager.GetString("not_escape_tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Escape Tile.
        /// </summary>
        internal static string not_escape_tile_title {
            get {
                return ResourceManager.GetString("not_escape_tile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To capture a treasure you have to be at a treasure tile.
        /// </summary>
        internal static string not_treasure_tile {
            get {
                return ResourceManager.GetString("not_treasure_tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Treasure Tile.
        /// </summary>
        internal static string not_treasure_tile_title {
            get {
                return ResourceManager.GetString("not_treasure_tile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not your turn yet, wait a little bit!.
        /// </summary>
        internal static string not_your_turn_message {
            get {
                return ResourceManager.GetString("not_your_turn_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s Not Your Turn.
        /// </summary>
        internal static string not_your_turn_title {
            get {
                return ResourceManager.GetString("not_your_turn_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string offline {
            get {
                return ResourceManager.GetString("offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string online_friends {
            get {
                return ResourceManager.GetString("online_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking Card.
        /// </summary>
        internal static string parking_card_name {
            get {
                return ResourceManager.GetString("parking_card_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a card.
        /// </summary>
        internal static string pick_card {
            get {
                return ResourceManager.GetString("pick_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} joined the match..
        /// </summary>
        internal static string player_joined {
            get {
                return ResourceManager.GetString("player_joined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} left the match..
        /// </summary>
        internal static string player_left {
            get {
                return ResourceManager.GetString("player_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is ready..
        /// </summary>
        internal static string player_ready {
            get {
                return ResourceManager.GetString("player_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not ready anymore..
        /// </summary>
        internal static string player_unready {
            get {
                return ResourceManager.GetString("player_unready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Verified.
        /// </summary>
        internal static string player_verified {
            get {
                return ResourceManager.GetString("player verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully verified.
        /// </summary>
        internal static string player_verified_message {
            get {
                return ResourceManager.GetString("player_verified_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the players with invitation can join .
        /// </summary>
        internal static string private_message {
            get {
                return ResourceManager.GetString("private_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any player can join in your game.
        /// </summary>
        internal static string public_message {
            get {
                return ResourceManager.GetString("public_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while retrieving info from the database.
        /// </summary>
        internal static string pull_database_error {
            get {
                return ResourceManager.GetString("pull_database_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while writing info to the database.
        /// </summary>
        internal static string push_database_error {
            get {
                return ResourceManager.GetString("push_database_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit game.
        /// </summary>
        internal static string quit_game {
            get {
                return ResourceManager.GetString("quit_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while closing application.
        /// </summary>
        internal static string quit_game_error {
            get {
                return ResourceManager.GetString("quit_game_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ready_button_ready {
            get {
                return ResourceManager.GetString("ready_button_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ready_button_start {
            get {
                return ResourceManager.GetString("ready_button_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unready.
        /// </summary>
        internal static string ready_button_unready {
            get {
                return ResourceManager.GetString("ready_button_unready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change the ready state (server error)..
        /// </summary>
        internal static string ready_failed {
            get {
                return ResourceManager.GetString("ready_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room {0}.
        /// </summary>
        internal static string room_default {
            get {
                return ResourceManager.GetString("room_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name.
        /// </summary>
        internal static string room_name {
            get {
                return ResourceManager.GetString("room_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string save_changes {
            get {
                return ResourceManager.GetString("save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search room....
        /// </summary>
        internal static string search_placeholder {
            get {
                return ResourceManager.GetString("search_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while sending your verification email, contact us at: forbbidenislandfei@gmail.com.
        /// </summary>
        internal static string send_email_error {
            get {
                return ResourceManager.GetString("send_email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shore up.
        /// </summary>
        internal static string shore_up_button {
            get {
                return ResourceManager.GetString("shore_up_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string show_password {
            get {
                return ResourceManager.GetString("show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string signup_button {
            get {
                return ResourceManager.GetString("signup_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while signing up, try again later.
        /// </summary>
        internal static string signup_error {
            get {
                return ResourceManager.GetString("signup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least 8 characters, one upper case, one lower case, one number and one special character (@, &amp;, _).
        /// </summary>
        internal static string signup_invalid_password {
            get {
                return ResourceManager.GetString("signup_invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string signup_title {
            get {
                return ResourceManager.GetString("signup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That user name is already being used.
        /// </summary>
        internal static string signup_username_already_used {
            get {
                return ResourceManager.GetString("signup_username_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the match (server error)..
        /// </summary>
        internal static string start_failed {
            get {
                return ResourceManager.GetString("start_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Sign-Up.
        /// </summary>
        internal static string successful_signup {
            get {
                return ResourceManager.GetString("successful_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sign-up was successful, now you can log in.
        /// </summary>
        internal static string successful_signup_message {
            get {
                return ResourceManager.GetString("successful_signup_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string system_prefix {
            get {
                return ResourceManager.GetString("system_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasures Saved.
        /// </summary>
        internal static string treasures_saved {
            get {
                return ResourceManager.GetString("treasures_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening tutorial..
        /// </summary>
        internal static string tutorial_open_error {
            get {
                return ResourceManager.GetString("tutorial_open_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error, please contact client support.
        /// </summary>
        internal static string unexpected_error {
            get {
                return ResourceManager.GetString("unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Avatar.
        /// </summary>
        internal static string upload_avatar {
            get {
                return ResourceManager.GetString("upload_avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Card.
        /// </summary>
        internal static string use_card {
            get {
                return ResourceManager.GetString("use_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        internal static string username_email {
            get {
                return ResourceManager.GetString("username_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username does not exists.
        /// </summary>
        internal static string usernameNoExists {
            get {
                return ResourceManager.GetString("usernameNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent you a new verification token, please check your email.
        /// </summary>
        internal static string verification_token_sent {
            get {
                return ResourceManager.GetString("verification_token_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Token Sent.
        /// </summary>
        internal static string verification_token_sent_title {
            get {
                return ResourceManager.GetString("verification_token_sent_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string verify {
            get {
                return ResourceManager.GetString("verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Account.
        /// </summary>
        internal static string verify_account {
            get {
                return ResourceManager.GetString("verify_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string visibility {
            get {
                return ResourceManager.GetString("visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string visibility_private {
            get {
                return ResourceManager.GetString("visibility_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string visibility_private_key {
            get {
                return ResourceManager.GetString("visibility_private_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string visibility_public {
            get {
                return ResourceManager.GetString("visibility_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string visibility_public_key {
            get {
                return ResourceManager.GetString("visibility_public_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning_title {
            get {
                return ResourceManager.GetString("warning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Level.
        /// </summary>
        internal static string water_level {
            get {
                return ResourceManager.GetString("water_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have saved all the treasures at the school! Thanks for playing!.
        /// </summary>
        internal static string win_message {
            get {
                return ResourceManager.GetString("win_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Win!.
        /// </summary>
        internal static string win_title {
            get {
                return ResourceManager.GetString("win_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Token.
        /// </summary>
        internal static string wrong_token {
            get {
                return ResourceManager.GetString("wrong_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token you try to verify is not correct, please try again.
        /// </summary>
        internal static string wrong_token_message {
            get {
                return ResourceManager.GetString("wrong_token_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        internal static string wrongPassword {
            get {
                return ResourceManager.GetString("wrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have drowned, better luck next time!.
        /// </summary>
        internal static string you_drowned_message {
            get {
                return ResourceManager.GetString("you_drowned_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s your turn to play! Choose wisely your actions.
        /// </summary>
        internal static string your_turn_message {
            get {
                return ResourceManager.GetString("your_turn_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Turn!.
        /// </summary>
        internal static string your_turn_title {
            get {
                return ResourceManager.GetString("your_turn_title", resourceCulture);
            }
        }
    }
}
