//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendsManager
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendsManager.IFriendsManager")]
    public interface IFriendsManager
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<FriendsManager.SendFriendRequestResponse> SendFriendRequestAsync(FriendsManager.SendFriendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/AcceptFriendRequestResponse")]
        System.Threading.Tasks.Task<FriendsManager.AcceptFriendRequestResponse> AcceptFriendRequestAsync(FriendsManager.AcceptFriendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/CancelFriendRequest", ReplyAction="http://tempuri.org/IFriendsManager/CancelFriendRequestResponse")]
        System.Threading.Tasks.Task<FriendsManager.CancelFriendRequestResponse> CancelFriendRequestAsync(FriendsManager.CancelFriendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/GetFriendRequests", ReplyAction="http://tempuri.org/IFriendsManager/GetFriendRequestsResponse")]
        System.Threading.Tasks.Task<FriendsManager.GetFriendRequestsResponse> GetFriendRequestsAsync(FriendsManager.GetFriendRequestsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsManager/GetFriendsByID", ReplyAction="http://tempuri.org/IFriendsManager/GetFriendsByIDResponse")]
        System.Threading.Tasks.Task<FriendsManager.GetFriendsByIDResponse> GetFriendsByIDAsync(FriendsManager.GetFriendsByIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFriendRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendFriendRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string senderUsername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string receiverUsername;
        
        public SendFriendRequestRequest()
        {
        }
        
        public SendFriendRequestRequest(string senderUsername, string receiverUsername)
        {
            this.senderUsername = senderUsername;
            this.receiverUsername = receiverUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFriendRequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendFriendRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendFriendRequestResult;
        
        public SendFriendRequestResponse()
        {
        }
        
        public SendFriendRequestResponse(bool SendFriendRequestResult)
        {
            this.SendFriendRequestResult = SendFriendRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AcceptFriendRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AcceptFriendRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string senderUsername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string receiverUsername;
        
        public AcceptFriendRequestRequest()
        {
        }
        
        public AcceptFriendRequestRequest(string senderUsername, string receiverUsername)
        {
            this.senderUsername = senderUsername;
            this.receiverUsername = receiverUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AcceptFriendRequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AcceptFriendRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AcceptFriendRequestResult;
        
        public AcceptFriendRequestResponse()
        {
        }
        
        public AcceptFriendRequestResponse(bool AcceptFriendRequestResult)
        {
            this.AcceptFriendRequestResult = AcceptFriendRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelFriendRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelFriendRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string senderUsername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string receiverUsername;
        
        public CancelFriendRequestRequest()
        {
        }
        
        public CancelFriendRequestRequest(string senderUsername, string receiverUsername)
        {
            this.senderUsername = senderUsername;
            this.receiverUsername = receiverUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelFriendRequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelFriendRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CancelFriendRequestResult;
        
        public CancelFriendRequestResponse()
        {
        }
        
        public CancelFriendRequestResponse(bool CancelFriendRequestResult)
        {
            this.CancelFriendRequestResult = CancelFriendRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFriendRequests", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFriendRequestsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string receiverUsername;
        
        public GetFriendRequestsRequest()
        {
        }
        
        public GetFriendRequestsRequest(string receiverUsername)
        {
            this.receiverUsername = receiverUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFriendRequestsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFriendRequestsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Forbbiden.Contracts.FriendRequest[] GetFriendRequestsResult;
        
        public GetFriendRequestsResponse()
        {
        }
        
        public GetFriendRequestsResponse(Forbbiden.Contracts.FriendRequest[] GetFriendRequestsResult)
        {
            this.GetFriendRequestsResult = GetFriendRequestsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFriendsByID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFriendsByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int playerID;
        
        public GetFriendsByIDRequest()
        {
        }
        
        public GetFriendsByIDRequest(int playerID)
        {
            this.playerID = playerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFriendsByIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFriendsByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Forbbiden.Contracts.Friendship[] GetFriendsByIDResult;
        
        public GetFriendsByIDResponse()
        {
        }
        
        public GetFriendsByIDResponse(Forbbiden.Contracts.Friendship[] GetFriendsByIDResult)
        {
            this.GetFriendsByIDResult = GetFriendsByIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IFriendsManagerChannel : FriendsManager.IFriendsManager, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class FriendsManagerClient : System.ServiceModel.ClientBase<FriendsManager.IFriendsManager>, FriendsManager.IFriendsManager
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FriendsManagerClient() : 
                base(FriendsManagerClient.GetDefaultBinding(), FriendsManagerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IFriendsManager.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FriendsManagerClient(EndpointConfiguration endpointConfiguration) : 
                base(FriendsManagerClient.GetBindingForEndpoint(endpointConfiguration), FriendsManagerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FriendsManagerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FriendsManagerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FriendsManagerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FriendsManagerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FriendsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<FriendsManager.SendFriendRequestResponse> SendFriendRequestAsync(FriendsManager.SendFriendRequestRequest request)
        {
            return base.Channel.SendFriendRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<FriendsManager.AcceptFriendRequestResponse> AcceptFriendRequestAsync(FriendsManager.AcceptFriendRequestRequest request)
        {
            return base.Channel.AcceptFriendRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<FriendsManager.CancelFriendRequestResponse> CancelFriendRequestAsync(FriendsManager.CancelFriendRequestRequest request)
        {
            return base.Channel.CancelFriendRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<FriendsManager.GetFriendRequestsResponse> GetFriendRequestsAsync(FriendsManager.GetFriendRequestsRequest request)
        {
            return base.Channel.GetFriendRequestsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FriendsManager.GetFriendsByIDResponse> GetFriendsByIDAsync(FriendsManager.GetFriendsByIDRequest request)
        {
            return base.Channel.GetFriendsByIDAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IFriendsManager))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IFriendsManager))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://localhost:8082/FriendsManager");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FriendsManagerClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IFriendsManager);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FriendsManagerClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IFriendsManager);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IFriendsManager,
        }
    }
}
