//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forbbiden.Server.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friends
    {
        public int player_id { get; set; }
        public int friend_id { get; set; }
        public int status { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Player Player2 { get; set; }
        public virtual Player Player3 { get; set; }
        public virtual Player Player4 { get; set; }
        public virtual Player Player5 { get; set; }
        public virtual Player Player6 { get; set; }
        public virtual Player Player7 { get; set; }
        public virtual Player Player8 { get; set; }
        public virtual Player Player9 { get; set; }
        public virtual Player Player10 { get; set; }
        public virtual Player Player11 { get; set; }
    }
}
