//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forbbiden.Server.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class match_minigames
    {
        public int match_minigames_id { get; set; }
        public int match_id { get; set; }
        public int minigame_id { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Minigame Minigame { get; set; }
    }
}
