//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forbbiden.Server.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tile()
        {
            this.Board = new HashSet<Board>();
        }
    
        public int tile_id { get; set; }
        public int col { get; set; }
        public int row { get; set; }
        public Nullable<int> is_treasure { get; set; }
        public Nullable<int> is_flood { get; set; }
        public Nullable<int> is_escape { get; set; }
        public Nullable<int> is_lost { get; set; }
        public string image_file_name { get; set; }
        public Nullable<int> treasure_card_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Board> Board { get; set; }
        public virtual Card Card { get; set; }
    }
}
