//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileManager
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class Fault : object
    {
        
        private string DetailsField;
        
        private string ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class Player : object
    {
        
        private ProfileManager.Friendship[] FriendsField;
        
        private int IsVerifiedField;
        
        private byte[] PlayerAvatarBytesField;
        
        private string PlayerAvatarNameField;
        
        private string PlayerEmailField;
        
        private int PlayerIdField;
        
        private string PlayerNameField;
        
        private string PlayerPasswordField;
        
        private string PlayerUsernameField;
        
        private ProfileManager.SocialMedia[] SocialMediaField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProfileManager.Friendship[] Friends
        {
            get
            {
                return this.FriendsField;
            }
            set
            {
                this.FriendsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsVerified
        {
            get
            {
                return this.IsVerifiedField;
            }
            set
            {
                this.IsVerifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PlayerAvatarBytes
        {
            get
            {
                return this.PlayerAvatarBytesField;
            }
            set
            {
                this.PlayerAvatarBytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerAvatarName
        {
            get
            {
                return this.PlayerAvatarNameField;
            }
            set
            {
                this.PlayerAvatarNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerEmail
        {
            get
            {
                return this.PlayerEmailField;
            }
            set
            {
                this.PlayerEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId
        {
            get
            {
                return this.PlayerIdField;
            }
            set
            {
                this.PlayerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName
        {
            get
            {
                return this.PlayerNameField;
            }
            set
            {
                this.PlayerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerPassword
        {
            get
            {
                return this.PlayerPasswordField;
            }
            set
            {
                this.PlayerPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerUsername
        {
            get
            {
                return this.PlayerUsernameField;
            }
            set
            {
                this.PlayerUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProfileManager.SocialMedia[] SocialMedia
        {
            get
            {
                return this.SocialMediaField;
            }
            set
            {
                this.SocialMediaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Friendship", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class Friendship : object
    {
        
        private ProfileManager.Player FriendField;
        
        private int PlayerIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProfileManager.Player Friend
        {
            get
            {
                return this.FriendField;
            }
            set
            {
                this.FriendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerID
        {
            get
            {
                return this.PlayerIDField;
            }
            set
            {
                this.PlayerIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialMedia", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class SocialMedia : object
    {
        
        private int PlayerIdField;
        
        private string SocialLinkField;
        
        private int SocialMediaIdField;
        
        private string SocialMediaNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId
        {
            get
            {
                return this.PlayerIdField;
            }
            set
            {
                this.PlayerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialLink
        {
            get
            {
                return this.SocialLinkField;
            }
            set
            {
                this.SocialLinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SocialMediaId
        {
            get
            {
                return this.SocialMediaIdField;
            }
            set
            {
                this.SocialMediaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialMediaName
        {
            get
            {
                return this.SocialMediaNameField;
            }
            set
            {
                this.SocialMediaNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvatarResponse", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class AvatarResponse : object
    {
        
        private byte[] AvatarBytesField;
        
        private string FileNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] AvatarBytes
        {
            get
            {
                return this.AvatarBytesField;
            }
            set
            {
                this.AvatarBytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileManager.IProfileManager")]
    public interface IProfileManager
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/IsEmailAvailable", ReplyAction="http://tempuri.org/IProfileManager/IsEmailAvailableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/IsEmailAvailableFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> IsEmailAvailableAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/IsUsernameAvailable", ReplyAction="http://tempuri.org/IProfileManager/IsUsernameAvailableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/IsUsernameAvailableFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> IsUsernameAvailableAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/SendSignupEmail", ReplyAction="http://tempuri.org/IProfileManager/SendSignupEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/SendSignupEmailFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> SendSignupEmailAsync(string email, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/SendVerificationEmail", ReplyAction="http://tempuri.org/IProfileManager/SendVerificationEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/SendVerificationEmailFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> SendVerificationEmailAsync(string email, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/SignUp", ReplyAction="http://tempuri.org/IProfileManager/SignUpResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/SignUpFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<int> SignUpAsync(ProfileManager.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/Login", ReplyAction="http://tempuri.org/IProfileManager/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/LoginFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<ProfileManager.Player> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/GetPlayerByUsername", ReplyAction="http://tempuri.org/IProfileManager/GetPlayerByUsernameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/GetPlayerByUsernameFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<ProfileManager.Player> GetPlayerByUsernameAsync(string username, bool includeFriends);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/GetPlayerById", ReplyAction="http://tempuri.org/IProfileManager/GetPlayerByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/GetPlayerByIdFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<ProfileManager.Player> GetPlayerByIdAsync(int playerId, bool includeFriends);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdatePlayer", ReplyAction="http://tempuri.org/IProfileManager/UpdatePlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/UpdatePlayerFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> UpdatePlayerAsync(ProfileManager.Player updatedPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/DeletePlayerByUsername", ReplyAction="http://tempuri.org/IProfileManager/DeletePlayerByUsernameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/DeletePlayerByUsernameFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> DeletePlayerByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/ConnectPlayerByUsername", ReplyAction="http://tempuri.org/IProfileManager/ConnectPlayerByUsernameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/ConnectPlayerByUsernameFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> ConnectPlayerByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/DisconnectPlayerByUsername", ReplyAction="http://tempuri.org/IProfileManager/DisconnectPlayerByUsernameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/DisconnectPlayerByUsernameFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> DisconnectPlayerByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/GetAvatar", ReplyAction="http://tempuri.org/IProfileManager/GetAvatarResponse")]
        System.Threading.Tasks.Task<byte[]> GetAvatarAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UploadAvatar", ReplyAction="http://tempuri.org/IProfileManager/UploadAvatarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/UploadAvatarFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> UploadAvatarAsync(string username, byte[] avatarBytes, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/GetAvatarByUsername", ReplyAction="http://tempuri.org/IProfileManager/GetAvatarByUsernameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.Fault), Action="http://tempuri.org/IProfileManager/GetAvatarByUsernameFaultFault", Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<ProfileManager.AvatarResponse> GetAvatarByUsernameAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IProfileManagerChannel : ProfileManager.IProfileManager, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ProfileManagerClient : System.ServiceModel.ClientBase<ProfileManager.IProfileManager>, ProfileManager.IProfileManager
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProfileManagerClient() : 
                base(ProfileManagerClient.GetDefaultBinding(), ProfileManagerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IProfileManager.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileManagerClient(EndpointConfiguration endpointConfiguration) : 
                base(ProfileManagerClient.GetBindingForEndpoint(endpointConfiguration), ProfileManagerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileManagerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProfileManagerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileManagerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProfileManagerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> IsEmailAvailableAsync(string email)
        {
            return base.Channel.IsEmailAvailableAsync(email);
        }
        
        public System.Threading.Tasks.Task<bool> IsUsernameAvailableAsync(string username)
        {
            return base.Channel.IsUsernameAvailableAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> SendSignupEmailAsync(string email, string token)
        {
            return base.Channel.SendSignupEmailAsync(email, token);
        }
        
        public System.Threading.Tasks.Task<bool> SendVerificationEmailAsync(string email, string token)
        {
            return base.Channel.SendVerificationEmailAsync(email, token);
        }
        
        public System.Threading.Tasks.Task<int> SignUpAsync(ProfileManager.Player player)
        {
            return base.Channel.SignUpAsync(player);
        }
        
        public System.Threading.Tasks.Task<ProfileManager.Player> LoginAsync(string username, string password)
        {
            return base.Channel.LoginAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<ProfileManager.Player> GetPlayerByUsernameAsync(string username, bool includeFriends)
        {
            return base.Channel.GetPlayerByUsernameAsync(username, includeFriends);
        }
        
        public System.Threading.Tasks.Task<ProfileManager.Player> GetPlayerByIdAsync(int playerId, bool includeFriends)
        {
            return base.Channel.GetPlayerByIdAsync(playerId, includeFriends);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePlayerAsync(ProfileManager.Player updatedPlayer)
        {
            return base.Channel.UpdatePlayerAsync(updatedPlayer);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePlayerByUsernameAsync(string username)
        {
            return base.Channel.DeletePlayerByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> ConnectPlayerByUsernameAsync(string username)
        {
            return base.Channel.ConnectPlayerByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> DisconnectPlayerByUsernameAsync(string username)
        {
            return base.Channel.DisconnectPlayerByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetAvatarAsync(string fileName)
        {
            return base.Channel.GetAvatarAsync(fileName);
        }
        
        public System.Threading.Tasks.Task<bool> UploadAvatarAsync(string username, byte[] avatarBytes, string fileName)
        {
            return base.Channel.UploadAvatarAsync(username, avatarBytes, fileName);
        }
        
        public System.Threading.Tasks.Task<ProfileManager.AvatarResponse> GetAvatarByUsernameAsync(string username)
        {
            return base.Channel.GetAvatarByUsernameAsync(username);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IProfileManager))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IProfileManager))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://192.168.100.15:8081/ProfileManager");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProfileManagerClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IProfileManager);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProfileManagerClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IProfileManager);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IProfileManager,
        }
    }
}
