//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileManager
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class DBFault : object
    {
        
        private string DetailsField;
        
        private string ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class EmailFault : object
    {
        
        private string DetailsField;
        
        private string ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class Player : object
    {
        
        private ProfileManager.Friendship[] FriendsField;
        
        private string PlayerAvatarPathField;
        
        private string PlayerEmailField;
        
        private int PlayerIdField;
        
        private string PlayerNameField;
        
        private string PlayerPasswordField;
        
        private string PlayerUsernameField;
        
        private ProfileManager.SocialMedia[] SocialMediaField;
        
        private int StatusField;
        
        private int VerifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProfileManager.Friendship[] Friends
        {
            get
            {
                return this.FriendsField;
            }
            set
            {
                this.FriendsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerAvatarPath
        {
            get
            {
                return this.PlayerAvatarPathField;
            }
            set
            {
                this.PlayerAvatarPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerEmail
        {
            get
            {
                return this.PlayerEmailField;
            }
            set
            {
                this.PlayerEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId
        {
            get
            {
                return this.PlayerIdField;
            }
            set
            {
                this.PlayerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName
        {
            get
            {
                return this.PlayerNameField;
            }
            set
            {
                this.PlayerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerPassword
        {
            get
            {
                return this.PlayerPasswordField;
            }
            set
            {
                this.PlayerPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerUsername
        {
            get
            {
                return this.PlayerUsernameField;
            }
            set
            {
                this.PlayerUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProfileManager.SocialMedia[] SocialMedia
        {
            get
            {
                return this.SocialMediaField;
            }
            set
            {
                this.SocialMediaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Verified
        {
            get
            {
                return this.VerifiedField;
            }
            set
            {
                this.VerifiedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Friendship", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class Friendship : object
    {
        
        private ProfileManager.Player FriendField;
        
        private int PlayerIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProfileManager.Player Friend
        {
            get
            {
                return this.FriendField;
            }
            set
            {
                this.FriendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerID
        {
            get
            {
                return this.PlayerIDField;
            }
            set
            {
                this.PlayerIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialMedia", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
    public partial class SocialMedia : object
    {
        
        private int PlayerIdField;
        
        private string SocialLinkField;
        
        private int SocialMediaIdField;
        
        private string SocialMediaNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId
        {
            get
            {
                return this.PlayerIdField;
            }
            set
            {
                this.PlayerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialLink
        {
            get
            {
                return this.SocialLinkField;
            }
            set
            {
                this.SocialLinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SocialMediaId
        {
            get
            {
                return this.SocialMediaIdField;
            }
            set
            {
                this.SocialMediaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialMediaName
        {
            get
            {
                return this.SocialMediaNameField;
            }
            set
            {
                this.SocialMediaNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileManager.IProfileManager")]
    public interface IProfileManager
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/ValidateEmail", ReplyAction="http://tempuri.org/IProfileManager/ValidateEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.DBFault), Action="http://tempuri.org/IProfileManager/ValidateEmailDBFaultFault", Name="DBFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> ValidateEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/IsUsernameAvailable", ReplyAction="http://tempuri.org/IProfileManager/IsUsernameAvailableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.DBFault), Action="http://tempuri.org/IProfileManager/IsUsernameAvailableDBFaultFault", Name="DBFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> IsUsernameAvailableAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/SendEmail", ReplyAction="http://tempuri.org/IProfileManager/SendEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.EmailFault), Action="http://tempuri.org/IProfileManager/SendEmailEmailFaultFault", Name="EmailFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> SendEmailAsync(string email, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/SignUp", ReplyAction="http://tempuri.org/IProfileManager/SignUpResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.DBFault), Action="http://tempuri.org/IProfileManager/SignUpDBFaultFault", Name="DBFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<int> SignUpAsync(ProfileManager.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/Login", ReplyAction="http://tempuri.org/IProfileManager/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.DBFault), Action="http://tempuri.org/IProfileManager/LoginDBFaultFault", Name="DBFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> LoginAsync(ProfileManager.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/GetPlayerByUsername", ReplyAction="http://tempuri.org/IProfileManager/GetPlayerByUsernameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.DBFault), Action="http://tempuri.org/IProfileManager/GetPlayerByUsernameDBFaultFault", Name="DBFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<ProfileManager.Player> GetPlayerByUsernameAsync(string username, bool includeFriends);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/GetPlayerById", ReplyAction="http://tempuri.org/IProfileManager/GetPlayerByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.DBFault), Action="http://tempuri.org/IProfileManager/GetPlayerByIdDBFaultFault", Name="DBFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<ProfileManager.Player> GetPlayerByIdAsync(int playerId, bool includeFriends);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/GetCurrentLogin", ReplyAction="http://tempuri.org/IProfileManager/GetCurrentLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.DBFault), Action="http://tempuri.org/IProfileManager/GetCurrentLoginDBFaultFault", Name="DBFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<ProfileManager.Player> GetCurrentLoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/ClearCurrentLogin", ReplyAction="http://tempuri.org/IProfileManager/ClearCurrentLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.DBFault), Action="http://tempuri.org/IProfileManager/ClearCurrentLoginDBFaultFault", Name="DBFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> ClearCurrentLoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdatePlayer", ReplyAction="http://tempuri.org/IProfileManager/UpdatePlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.DBFault), Action="http://tempuri.org/IProfileManager/UpdatePlayerDBFaultFault", Name="DBFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> UpdatePlayerAsync(ProfileManager.Player updatedPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/DeletePlayerByUsername", ReplyAction="http://tempuri.org/IProfileManager/DeletePlayerByUsernameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProfileManager.DBFault), Action="http://tempuri.org/IProfileManager/DeletePlayerByUsernameDBFaultFault", Name="DBFault", Namespace="http://schemas.datacontract.org/2004/07/Forbbiden.Contracts")]
        System.Threading.Tasks.Task<bool> DeletePlayerByUsernameAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IProfileManagerChannel : ProfileManager.IProfileManager, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ProfileManagerClient : System.ServiceModel.ClientBase<ProfileManager.IProfileManager>, ProfileManager.IProfileManager
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProfileManagerClient() : 
                base(ProfileManagerClient.GetDefaultBinding(), ProfileManagerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IProfileManager.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileManagerClient(EndpointConfiguration endpointConfiguration) : 
                base(ProfileManagerClient.GetBindingForEndpoint(endpointConfiguration), ProfileManagerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileManagerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProfileManagerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileManagerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProfileManagerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> ValidateEmailAsync(string email)
        {
            return base.Channel.ValidateEmailAsync(email);
        }
        
        public System.Threading.Tasks.Task<bool> IsUsernameAvailableAsync(string username)
        {
            return base.Channel.IsUsernameAvailableAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> SendEmailAsync(string email, int playerId)
        {
            return base.Channel.SendEmailAsync(email, playerId);
        }
        
        public System.Threading.Tasks.Task<int> SignUpAsync(ProfileManager.Player player)
        {
            return base.Channel.SignUpAsync(player);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(ProfileManager.Player player)
        {
            return base.Channel.LoginAsync(player);
        }
        
        public System.Threading.Tasks.Task<ProfileManager.Player> GetPlayerByUsernameAsync(string username, bool includeFriends)
        {
            return base.Channel.GetPlayerByUsernameAsync(username, includeFriends);
        }
        
        public System.Threading.Tasks.Task<ProfileManager.Player> GetPlayerByIdAsync(int playerId, bool includeFriends)
        {
            return base.Channel.GetPlayerByIdAsync(playerId, includeFriends);
        }
        
        public System.Threading.Tasks.Task<ProfileManager.Player> GetCurrentLoginAsync()
        {
            return base.Channel.GetCurrentLoginAsync();
        }
        
        public System.Threading.Tasks.Task<bool> ClearCurrentLoginAsync()
        {
            return base.Channel.ClearCurrentLoginAsync();
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePlayerAsync(ProfileManager.Player updatedPlayer)
        {
            return base.Channel.UpdatePlayerAsync(updatedPlayer);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePlayerByUsernameAsync(string username)
        {
            return base.Channel.DeletePlayerByUsernameAsync(username);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IProfileManager))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IProfileManager))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://localhost:8081/ProfileManager");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProfileManagerClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IProfileManager);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProfileManagerClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IProfileManager);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IProfileManager,
        }
    }
}
