//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forbbiden.Client.MatchNotificationManager {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchNotificationManager.IMatchNotificationManager", CallbackContract=typeof(Forbbiden.Client.MatchNotificationManager.IMatchNotificationManagerCallback))]
    public interface IMatchNotificationManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationManager/Subscribe", ReplyAction="http://tempuri.org/IMatchNotificationManager/SubscribeResponse")]
        void Subscribe(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationManager/Subscribe", ReplyAction="http://tempuri.org/IMatchNotificationManager/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationManager/Unsubscribe", ReplyAction="http://tempuri.org/IMatchNotificationManager/UnsubscribeResponse")]
        void Unsubscribe(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchNotificationManager/Unsubscribe", ReplyAction="http://tempuri.org/IMatchNotificationManager/UnsubscribeResponse")]
        System.Threading.Tasks.Task UnsubscribeAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchNotificationManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchNotificationManager/OnBoardCreatedCallback")]
        void OnBoardCreatedCallback(string boardJson);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchNotificationManager/OnBoardUpdatedCallback")]
        void OnBoardUpdatedCallback(string boardJson);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchNotificationManager/OnPlayersTurnCallback")]
        void OnPlayersTurnCallback();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchNotificationManager/OnTurnFinishedCallback")]
        void OnTurnFinishedCallback(string boardJson);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchNotificationManagerChannel : Forbbiden.Client.MatchNotificationManager.IMatchNotificationManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchNotificationManagerClient : System.ServiceModel.DuplexClientBase<Forbbiden.Client.MatchNotificationManager.IMatchNotificationManager>, Forbbiden.Client.MatchNotificationManager.IMatchNotificationManager {
        
        public MatchNotificationManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchNotificationManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchNotificationManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchNotificationManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchNotificationManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe(string username) {
            base.Channel.Subscribe(username);
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(string username) {
            return base.Channel.SubscribeAsync(username);
        }
        
        public void Unsubscribe(string username) {
            base.Channel.Unsubscribe(username);
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync(string username) {
            return base.Channel.UnsubscribeAsync(username);
        }
    }
}
